package/systemd: fix statx support with glibc >= 2.28
Backport 2 patches fixing statx redefinition:

  In file included from ../src/basic/missing.h:18,
     from ../src/basic/util.h:28,
     from ../src/basic/hashmap.h:10,
     from ../src/shared/bus-util.h:12,
     from ../src/libsystemd/sd-bus/bus-creds.c:11:
     /usr/include/linux/stat.h:99:8: error: redefinition of ‘struct statx’

Signed-off-by: Romain Naour <romain.naour@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit 7eed608713be61ea42c0cf45dd535c03fc2d346b)

Change-Id: Ie14efbd1191f5515dec877ed0d29c6a6630ae95d
Signed-off-by: Jeffy Chen <jeffy.chen@rock-chips.com>